name: Release and Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm run test
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  verify:
    name: Verify npm install and CLI
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Verify installed binaries
        run: |
          set -euo pipefail
          # Verify global npx can run the package and binaries are resolvable
          npx -y @get2knowio/n8n-mcp n8n-mcp --help || true
          npx -y @get2knowio/n8n-mcp n8n-mcp-server --help || true
          # Check that commands are available via npx resolution
          command -v npx >/dev/null 2>&1 && echo "npx exists"